greenGrocery/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('update/', views.cart_update, name='update'),
    path('remove_in_cart/', views.in_cart_remove, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('success/', views.success, name='success'),
    path('api/', views.cart_api, name='api')
]

greenGrocery/greenGrocery/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from . import views
from user import urls as user_urls
from products import urls as product_urls
from carts import urls as cart_urls
from billing import urls as billing_urls
from contact import urls as contact_urls

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('subscription', views.subscription, name='subscription'),
    path('admin/', admin.site.urls),
    path('', include(user_urls)),
    path('products/', include(product_urls)),
    path('cart/', include(cart_urls)),
    path('billing/', include(billing_urls)),
    path('contact/', include(contact_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

greenGrocery/products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='products'),
    path('vegetables/', views.vegetables, name='vegetables'),
    path('fruits/', views.fruits, name='fruits'),
    path('featured/', views.featured, name='featured'),
    path('sale/', views.sale, name='sale'),

    path('<slug:slug>/', views.all_products, name='products'),
    path('vegetables/<slug:slug>/', views.vegetables, name='vegetables'),
    path('fruits/<slug:slug>/', views.fruits, name='fruits'),
    path('featured/<slug:slug>/', views.featured, name='featured'),
    path('sale/<slug:slug>/', views.sale, name='sale'),
]

greenGrocery/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('register/guest', views.guest_register_view, name='guest_register'),
    path('logout/', views.logoutView, name='logout')
]

greenGrocery/carts/models.py
from django.db import models

from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.contrib.auth.models import User

# Create your models here.

# User = settings.AUTH_USER_MODEL


class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get('cart_id', None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            cart_obj = qs.first()
            new_obj = False
            if request.user.is_authenticated and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated:
                user_obj = user
        return self.model.objects.create(user=user_obj)


class Cart(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    products = models.ManyToManyField(
        to=Product,
        blank=True
    )
    subtotal = models.DecimalField(
        default=0.00,
        max_digits=100,
        decimal_places=2
    )
    discount_amount = models.DecimalField(
        'Discount Amount',
        default=0.00,
        max_digits=100,
        decimal_places=2
    )
    total = models.DecimalField(
        default=0.00,
        max_digits=100,
        decimal_places=2
    )
    updated = models.DateTimeField(auto_now=True)
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)

    def update_discount_total(self, coupon):
        if coupon == 'green' and self.subtotal >= 150:
            discount = float(self.subtotal) * 0.5
            if discount > 100:
                discount = 100
            self.discount_amount = discount
            self.save()
            return 'success'
        else:
            return 'error'


def cart_m2m_changed_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            if x.on_sale:
                x.price = x.discounted_price * CartItem.objects.get(
                    item=x, item_cart=instance.id).quantity
            total += x.price * CartItem.objects.get(
                item=x, item_cart=instance.id).quantity
        instance.subtotal = total
        instance.save()


m2m_changed.connect(cart_m2m_changed_receiver, sender=Cart.products.through)


def cart_pre_save_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal < 100:
        instance.total = instance.subtotal + 20
    else:
        instance.total = instance.subtotal

    instance.total = float(instance.total) - float(instance.discount_amount)


pre_save.connect(cart_pre_save_receiver, sender=Cart)


class CartItem(models.Model):
    item = models.OneToOneField(
        to=Product,
        on_delete=models.CASCADE
    )
    item_cart = models.ForeignKey(
        to=Cart,
        on_delete=models.CASCADE
    )
    quantity = models.IntegerField(
        default=1,
        null=True,
        blank=True
    )

    def __str__(self):
        return str(self.item_cart)

greenGrocery/carts/views.py
from django.shortcuts import render, redirect
from django.http import JsonResponse
from decimal import Decimal

from .models import Cart, CartItem
from orders.models import Order
from products.models import Product
from billing.models import BillingProfile
from user.forms import GuestForm
from user.models import GuestEmail
from addresses.forms import AddressForm
from addresses.models import Address

from django.contrib import messages

# Create your views here.


def cart_api(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{"image": x.image.url, "title": x.title, "price": x.price}
                for x in cart_obj.products.all()]
    return JsonResponse({
        "products": products,
        "subtotal": cart_obj.subtotal,
        "discount_amount": cart_obj.discount_amount,
        "total": cart_obj.total
    })


def cart(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    discount = f'{0:.2f}'
    cart_obj.discount_amount = discount
    cart_obj.save()
    quantity_dict = {}
    for product in cart_obj.products.all():
        quantity = CartItem.objects.get(
            item=product, item_cart=cart_obj).quantity
        quantity_dict[product] = quantity
    if request.POST:
        coupon = request.POST.get('coupon').lower()
        discount_response = cart_obj.update_discount_total(coupon)
        if discount_response == 'success':
            messages.success(
                request, f'Coupon applied successfully. You have saved ₹{cart_obj.discount_amount} on your cart.')
        else:
            messages.error(request, 'Invalid coupon or cart value')
    my_dict = {
        'cart': cart_obj,
        'quantity': quantity_dict
    }
    return render(request, 'carts/cart.html', my_dict)


def cart_update(request):
    product_id = request.POST.get('product_id')
    quantity = int(request.POST.get('quantity'))
    product_obj = Product.objects.get(id=product_id)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    item, created = CartItem.objects.get_or_create(
        item=product_obj, item_cart=cart_obj)
    if quantity not in range(1, 11):
        pass
    if product_obj in cart_obj.products.all():
        qs = CartItem.objects.get(
            item=product_obj, item_cart=cart_obj)
        actual_quantity = qs.quantity
        if quantity < actual_quantity and quantity != 0:
            request.session['quantity'] = quantity
            CartItem.objects.filter(item=product_obj, item_cart=cart_obj).update(
                quantity=quantity)
        else:
            item.delete()
            request.session['quantity'] = 1
            cart_obj.products.remove(product_obj)
            product_added = False
    else:
        if quantity > 0:
            CartItem.objects.filter(item=product_obj, item_cart=cart_obj).update(
                quantity=quantity)
            request.session['quantity'] = quantity
            cart_obj.products.add(product_obj)
            product_added = True
    request.session['cart_items_total'] = cart_obj.products.count()
    if request.is_ajax():
        # print("Ajax Request")
        json_data = {
            "added": product_added,
            "removed": not product_added,
            "cartItemCount": cart_obj.products.count()
        }
        return JsonResponse(json_data)
    return redirect(product_obj.get_absolute_url())


def in_cart_remove(request):
    product_id = request.POST.get('product_id')
    product_obj = Product.objects.get(id=product_id)
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    item, created = CartItem.objects.get_or_create(
        item=product_obj, item_cart=cart_obj)
    if product_obj in cart_obj.products.all():
        item.delete()
        request.session['quantity'] = 1
        cart_obj.products.remove(product_obj)
    request.session['cart_items_total'] = cart_obj.products.count()
    return redirect('carts:cart')


def success(request):
    return render(request, "carts/success.html")


def checkout(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect('carts:cart')
    guest_form = GuestForm()
    address_form = AddressForm(request.POST or None)
    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(
        request)
    if address_form.is_valid():
        instance = address_form.save(commit=False)
        instance.billing_profile = billing_profile
        instance.save()
        request.session['delivery_address_id'] = instance.id
    delivery_address_id = request.session.get('delivery_address_id', None)
    address_qs = None
    if billing_profile is not None:
        address_qs = Address.objects.filter(billing_profile=billing_profile)
        if address_qs.count() >= 1:
            address_qs = address_qs.first()
        order_obj, order_obj_created = Order.objects.new_or_get(
            billing_profile, cart_obj)
        if delivery_address_id:
            order_obj.delivery_address = Address.objects.get(
                id=delivery_address_id)
            del request.session['delivery_address_id']
            order_obj.save()
    if request.method == 'POST':
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items_total'] = 0
            del request.session['cart_id']
            return redirect('carts:success')
    my_dict = {
        'order': order_obj,
        'cart': cart_obj,
        'billing_profile': billing_profile,
        'address_form': address_form,
        'address_qs': address_qs,
    }
    return render(request, 'carts/checkout.html', my_dict)

greenGrocery/templates/carts/cart.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
{% load extras %}
<div class="hero-wrap hero-bread" style="background-image: url('{% static 'images/market-4.jpg' %}');">
    <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
            <div class="col-md-9 ftco-animate text-center">
                <p class="breadcrumbs">
                    <span class="mr-2"><a href="index.html">Home</a></span>
                    <span>Cart</span>
                </p>
                <h1 class="mb-0 bread">My Cart</h1>
            </div>
        </div>
    </div>
</div>

{% if cart.products.exists %}
<section class="ftco-section ftco-cart">
    <div class="container">
        <div class="row">
            <div class="col-md-12 ftco-animate">
                <div class="cart-list">
                    <table class="table cart-table">
                        <thead class="thead-primary">
                            <tr class="text-center">
                                <th>&nbsp;</th>
                                <th>&nbsp;</th>
                                <th>Product name</th>
                                <th>Price</th>
                                <th>Quantity</th>
                                <th>Total</th>
                            </tr>
                        </thead>
                        <tbody class="cart-body">
                            {% for product in cart.products.all %}
                            <tr class="text-center">
                                <td class="product-remove">
                                    {% include 'products/snippets/update-cart.html' with product=product cart=cart in_cart=True%}
                                    <!-- <a href="#"><span class="ion-ios-close"></span></a> -->
                                </td>

                                <td class="image-prod">
                                    <a href="{{ product.image.url }}" class="image-popup"><img
                                            src="{{ product.image.url }}" width="100" height="100" class="img-fluid"
                                            alt="" /></a>
                                </td>

                                <td class="product-name">
                                    <h3>{{ product.title }}</h3>
                                    <!-- <p>
                                        {{ product.description }}
                                    </p> -->
                                </td>

                                {% if product.on_sale %}
                                <td class="price"> ₹{{ product.discounted_price }} </td>
                                {% else %}
                                <td class="price"> ₹{{ product.price }} </td>
                                {% endif %}

                                <td class="quantity">
                                    <div class="input-group mb-3">
                                        {% for key, value in quantity.items %}
                                        {% if key == product %}
                                        <input type="text" name="quantity" class="quantity form-control input-number"
                                            value="{{ value }}" readonly />
                                        {% endif %}
                                        {% endfor %}
                                    </div>
                                </td>

                                {% for key, value in quantity.items %}
                                {% if key == product %}
                                {% if product.on_sale %}
                                <td class="price"> ₹{% multiply product.discounted_price value %} </td>
                                {% else %}
                                <td class="price"> ₹{% multiply product.price value %} </td>
                                {% endif %}
                                {% endif %}
                                {% endfor %}

                            </tr>
                            <!-- END TR-->
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row justify-content-end">
            <div class="col-lg-6 mt-5 cart-wrap ftco-animate">
                <form method="POST" action="{% url 'carts:cart' %}" class="info"> {% csrf_token %}
                    <div class="cart-total mb-3">
                        <h3>Coupon Code</h3>
                        <p>Enter your coupon code if you have one</p>

                        <div class="form-group">
                            <label for="coupon">Coupon code</label>
                            <input id="coupon" name="coupon" type="text" class="form-control text-left px-3"
                                placeholder="" value="{{ request.GET.coupon }}" />
                            <small class="form-text">- Apply GREEN to avail 50% off upto ₹100 on minimum cart value of
                                ₹150</small>
                            {% for message in messages %}
                            {% if message.tags == 'error' %}
                            <div class="alert alert-danger mt-3">
                                <a class="close" href="#" data-dismiss="alert">×</a>

                                {{ message }}

                            </div>
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>

                    <p>
                        <input type="submit" class="btn btn-primary styled-border px-4" value="Apply Coupon">
                    </p>

                </form>
            </div>
            <div class="col-lg-6 mt-5 cart-wrap ftco-animate">
                <div class="cart-total mb-3">
                    {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div class="alert alert-success">
                        <a class="close" href="#" data-dismiss="alert">×</a>

                        {{ message }}

                    </div>
                    {% endif %}
                    {% endfor %}
                    <h3>Cart Totals</h3>
                    <p class="d-flex">
                        <span>Subtotal</span>
                        <span>₹{{ cart.subtotal }}</span>
                    </p>
                    <p class="d-flex">
                        <span>Delivery</span>
                        {% if cart.subtotal < 100 %}
                        <span>₹20.00</span>
                        {% else %}
                        <span>₹0.00</span>
                        {% endif %}
                    </p>
                    <p class="d-flex">
                        <span>Discount</span>
                        <span>₹{{ cart.discount_amount }}</span>
                    </p>
                    <hr />
                    <p class="d-flex total-price">
                        <span>Total</span>
                        <span>₹{{ cart.total }}</span>
                    </p>
                </div>
                <p class="d-flex justify-content-between">
                    <a href="{% url 'carts:checkout' %}" class="btn btn-primary styled-border px-4">Proceed to
                        Checkout</a>
                    <span class="align-self-end">OR</span>
                    <a href="{% url 'products:products' %}"
                        class="btn btn-secondary border-secondary styled-border">Continue
                        Shopping</a>
                </p>
            </div>
        </div>
    </div>
</section>
{% else %}
<div class="container my-5 text-center">
    <div class="row">
        <div class="col">
            <p class="lead">Please add some products in cart...</p>
            <p><a href="{% url 'products:products' %}" class="btn btn-primary styled-border">Go to
                    Products</a></p>
        </div>
    </div>
</div>
{% endif %}

{% endblock %}

greenGrocery/templates/carts/success.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
<p>Success</p>
{% endblock %}