greenGrocery/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('update/', views.cart_update, name='update'),
    path('remove_in_cart/', views.in_cart_remove, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('success/', views.success, name='success'),
    path('api/', views.cart_api, name='api')
]

greenGrocery/greenGrocery/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from . import views
from user import urls as user_urls
from products import urls as product_urls
from carts import urls as cart_urls
from billing import urls as billing_urls
from contact import urls as contact_urls

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('subscription', views.subscription, name='subscription'),
    path('admin/', admin.site.urls),
    path('', include(user_urls)),
    path('products/', include(product_urls)),
    path('cart/', include(cart_urls)),
    path('billing/', include(billing_urls)),
    path('contact/', include(contact_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

greenGrocery/products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='products'),
    path('vegetables/', views.vegetables, name='vegetables'),
    path('fruits/', views.fruits, name='fruits'),
    path('featured/', views.featured, name='featured'),
    path('sale/', views.sale, name='sale'),

    path('<slug:slug>/', views.all_products, name='products'),
    path('vegetables/<slug:slug>/', views.vegetables, name='vegetables'),
    path('fruits/<slug:slug>/', views.fruits, name='fruits'),
    path('featured/<slug:slug>/', views.featured, name='featured'),
    path('sale/<slug:slug>/', views.sale, name='sale'),
]

greenGrocery/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('register/guest', views.guest_register_view, name='guest_register'),
    path('logout/', views.logoutView, name='logout')
]

greenGrocery/products/models.py
import os
import random
from django.db import models
from django.db.models import Q
from greenGrocery.utils import unique_slug_generator
from django.db.models.signals import pre_save, post_save
from django.urls import reverse

# Create your models here.


def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(filepath)
    return name, ext


def upload_image_path(instance, filename):
    new_filename = random.randint(1, 100000000)
    name, ext = get_filename_ext(filename)
    final_filename = f'{new_filename}{ext}'
    return f"products/{new_filename}/{final_filename}"


class IntegerRangeField(models.IntegerField):
    def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
        self.min_value, self.max_value = min_value, max_value
        models.IntegerField.__init__(self, verbose_name, name, **kwargs)

    def formfield(self, **kwargs):
        defaults = {'min_value': self.min_value, 'max_value': self.max_value}
        defaults.update(kwargs)
        return super(IntegerRangeField, self).formfield(**defaults)


class ProductQuerySet(models.query.QuerySet):
    def search(self, query):
        lookups = Q(title__icontains=query) | Q(description__icontains=query) | Q(
            price__iexact=query) | Q(tag__title__icontains=query)
        return self.filter(lookups).distinct()


class ProductManager(models.Manager):
    def get_queryset(self):
        return ProductQuerySet(self.model, using=self._db)

    def slug(self, slug):
        return self.get_queryset().filter(slug=slug)

    def featured(self):
        return self.get_queryset().filter(is_featured=True)

    def sale(self):
        return self.get_queryset().filter(on_sale=True)

    def vegetables(self):
        return self.get_queryset().filter(product_type='V')

    def fruits(self):
        return self.get_queryset().filter(product_type='F')

    def get_by_id(self, id):
        qs = self.get_queryset().filter(id=id)
        if qs.count == 1:
            return qs.first()
        return None

    def search(self, query):
        return self.get_queryset().search(query)


class Product(models.Model):
    PRODUCT_TYPES = [
        ('V', 'Vegetable'),
        ('F', 'Fruit')
    ]
    product_type = models.CharField(
        max_length=1,
        choices=PRODUCT_TYPES,
        default='V'
    )
    title = models.CharField(
        "Title",
        max_length=50,
        null=True
    )
    slug = models.SlugField(
        blank=True
    )
    description = models.TextField(
        "Description",
        max_length=500
    )
    price = models.DecimalField(
        "Price",
        decimal_places=2,
        max_digits=5
    )
    image = models.ImageField(
        "Image",
        upload_to=upload_image_path,
        null=True,
        blank=False
    )
    is_featured = models.BooleanField(
        "Featured",
        default=False
    )
    on_sale = models.BooleanField(
        "On Sale",
        default=False
    )
    discount = IntegerRangeField(
        "Discount for Sale",
        null=True,
        blank=True,
        min_value=10,
        max_value=60
    )
    discounted_price = models.DecimalField(
        "Price after discount",
        decimal_places=2,
        max_digits=5,
        null=True,
        blank=True
    )

    objects = ProductManager()

    def get_absolute_url(self):
        return reverse('products:products', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title


def product_pre_save_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)
    if instance.on_sale:
        instance.discounted_price = instance.price - \
            ((instance.price * instance.discount) / 100)


pre_save.connect(product_pre_save_receiver, sender=Product)

greenGrocery/products/views.py
from django.shortcuts import render
from django.http import Http404

from carts.models import Cart
from .models import Product

from analytics.signals import object_viewed_signal

lst = ['Dragon Fruit', 'Papaya', 'Pineapple', 'Sugarcane']


def all_products(request, slug=None):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    query = request.GET.get('q')
    if query:
        qs = Product.objects.all().search(query)
    else:
        qs = Product.objects.all().order_by('?')
    dict = {
        'qs': qs,
        'btn': 'all_products',
        'lst': lst,
        'query': query,
        'cart': cart_obj
    }
    context = slug_fun(slug)
    if context:
        context.update(dict)
        return render(request, 'products/product_detail.html', context)
    return render(request, "products/index.html", dict)


def vegetables(request, slug=None):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    query = request.GET.get('q')
    if query:
        # Product.objects.vegetables().filter(title__icontains=query)
        qs = Product.objects.vegetables().search(query)
    else:
        qs = Product.objects.vegetables()
    dict = {
        'qs': qs,
        'btn': 'vegetables',
        'lst': lst,
        'query': query,
        'cart': cart_obj
    }
    context = slug_fun(slug)
    if context:
        context.update(dict)
        return render(request, 'products/product_detail.html', context)
    return render(request, "products/index.html", dict)


def fruits(request, slug=None):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    query = request.GET.get('q')
    if query:
        qs = Product.objects.fruits().search(query)
    else:
        qs = Product.objects.fruits()
    dict = {
        'qs': qs,
        'btn': 'fruits',
        'lst': lst,
        'query': query,
        'cart': cart_obj
    }
    context = slug_fun(slug)
    if context:
        context.update(dict)
        return render(request, 'products/product_detail.html', context)
    return render(request, "products/index.html", dict)


def featured(request, slug=None):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    query = request.GET.get('q')
    if query:
        qs = Product.objects.featured().search(query)
    else:
        qs = Product.objects.featured()
    dict = {
        'qs': qs,
        'btn': 'featured',
        'lst': lst,
        'query': query,
        'cart': cart_obj
    }
    context = slug_fun(slug)
    if context:
        context.update(dict)
        return render(request, 'products/product_detail.html', context)
    return render(request, "products/index.html", dict)


def sale(request, slug=None):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    query = request.GET.get('q')
    if query:
        qs = Product.objects.sale().search(query)
    else:
        qs = Product.objects.sale().order_by('-discount')
    dict = {
        'qs': qs,
        'btn': 'sale',
        'lst': lst,
        'query': query,
        'cart': cart_obj
    }
    context = slug_fun(slug)
    if context:
        context.update(dict)
        return render(request, 'products/product_detail.html', context)
    return render(request, "products/index.html", dict)


def slug_fun(slug):
    context = {}
    if slug != None:
        q = Product.objects.slug(slug)
        if q.exists():
            q = q.first()
        else:
            raise Http404('Not Found...')
        context = {
            'q': q
        }
    return context

greenGrocery/templates/products/snippets/search-form.html
<form class="search-form col-lg-5 mb-5 text-center" method="GET" {% if btn == 'all_products' %}
    action="{% url 'products:products' %}" {% elif btn == 'vegetables' %} action="{% url 'products:vegetables' %}"
    {% elif btn == 'fruits' %} action="{% url 'products:fruits' %}" {% elif btn == 'featured' %}
    action="{% url 'products:featured' %}" {% elif btn == 'sale' %} action="{% url 'products:sale' %}" {% endif %}>
    <div class="form-group d-flex">
        <input type="text" class="form-control rounded-0" name='q' value='{{ request.GET.q }}' placeholder="Search...">
        <input type="submit" value="Search" class="submit px-3" />
    </div>
</form>

greenGrocery/templates/products/snippets/update-cart.html
{% if in_cart %}
<form class="form-product-ajax" action='{% url "carts:remove" %}' data-endpoint='{% url "carts:update" %}'
    method="POST">{% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <input type='submit' class="btn btn-danger px-3 py-2 styled-border border border-black" value='x'>
</form>
{% else %}
<form class="form-product-ajax" action='{% url "carts:update" %}' data-endpoint='{% url "carts:update" %}'
    method="POST">{% csrf_token %}
    <input type="hidden" name="product_id" value="{{ product.id }}">
    <span class="submit-span">
        <div class="input-group col-md-6 d-flex mt-3 px-3 py-2">
            <span class="input-group-btn mr-2">
                <button type="button" class="quantity-left-minus btn" data-type="minus" data-field="">
                    <i class="ion-ios-remove"></i>
                </button>
            </span>
            <input type="text" id="quantity" name="quantity" class="form-control input-number"
                value="{% if request.session.quantity %}{{ request.session.quantity }}{% else %}1{% endif %}" min="1"
                max="10" readonly />
            <span class="input-group-btn ml-2">
                <button type="button" class="quantity-right-plus btn" data-type="plus" data-field="">
                    <i class="ion-ios-add"></i>
                </button>
            </span>
        </div>
        {% if product in cart.products.all %}
        <div class="d-flex">
            <input type='submit' class="btn btn-danger mt-3 mr-5 px-3 py-2 styled-border border border-black"
                value='Remove'>
            <a href="{% url 'carts:cart' %}" class="mt-3 px-3 py-2"><span
                    class="icon-shopping_cart"></span>[{{ cart.products.all.count }}]</a>
            {% for message in messages %}
            <div class="alert alert-danger">
                <a class="close" href="#" data-dismiss="alert">×</a>

                {{ message }}

            </div>
            {% endfor %}
        </div>
        {% else %}
        <input type='submit' class="btn btn-black mt-3 px-3 py-2 styled-border cart" value='Add to Cart'>
        {% endif %}
    </span>
</form>
{% endif %}