greenGrocery/carts/urls.py
from django.urls import path
from . import views

app_name = 'carts'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('update/', views.cart_update, name='update'),
    path('remove_in_cart/', views.in_cart_remove, name='remove'),
    path('checkout/', views.checkout, name='checkout'),
    path('success/', views.success, name='success'),
    path('api/', views.cart_api, name='api')
]

greenGrocery/contact/urls.py
from django.urls import path

from .views import contact_page

app_name = 'contact'

urlpatterns = [
    path('', contact_page, name='contact')
]

greenGrocery/greenGrocery/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import path, include

from . import views
from user import urls as user_urls
from products import urls as product_urls
from carts import urls as cart_urls
from billing import urls as billing_urls
from contact import urls as contact_urls

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('subscription', views.subscription, name='subscription'),
    path('admin/', admin.site.urls),
    path('', include(user_urls)),
    path('products/', include(product_urls)),
    path('cart/', include(cart_urls)),
    path('billing/', include(billing_urls)),
    path('contact/', include(contact_urls)),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

greenGrocery/products/urls.py
from django.urls import path
from .import views

app_name = 'products'

urlpatterns = [
    path('', views.all_products, name='products'),
    path('vegetables/', views.vegetables, name='vegetables'),
    path('fruits/', views.fruits, name='fruits'),
    path('featured/', views.featured, name='featured'),
    path('sale/', views.sale, name='sale'),

    path('<slug:slug>/', views.all_products, name='products'),
    path('vegetables/<slug:slug>/', views.vegetables, name='vegetables'),
    path('fruits/<slug:slug>/', views.fruits, name='fruits'),
    path('featured/<slug:slug>/', views.featured, name='featured'),
    path('sale/<slug:slug>/', views.sale, name='sale'),
]

greenGrocery/user/urls.py
from django.urls import path
from . import views

app_name = 'user'

urlpatterns = [
    path('login/', views.loginView, name='login'),
    path('register/', views.registerView, name='register'),
    path('register/guest', views.guest_register_view, name='guest_register'),
    path('logout/', views.logoutView, name='logout')
]

greenGrocery/contact/models.py
from django.db import models

# Create your models here.


class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=70, default="")
    subject = models.CharField(max_length=70, default="")
    message = models.CharField(
        max_length=500, default="", null=True, blank=True)
    timestamp = models.DateTimeField(
        auto_now_add=True,
        # null=True
    )

    def __str__(self):
        return self.name

greenGrocery/contact/forms.py
from django import forms
from django.core import validators

from .models import Contact


class ContactForm(forms.ModelForm):
    name = forms.CharField(
        label="Name",
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your Name'
            }
        ),
        validators=[
            validators.RegexValidator(
                regex='^[A-Za-z ]{3,50}$', message="Must be valid...")
        ]
    )
    email = forms.CharField(
        label="Email",
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Your Email'
            }
        ),
        validators=[
            validators.RegexValidator(
                regex='^\w+@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$', message="Must be valid...")
        ]
    )
    subject = forms.CharField(
        label="Subject",
        max_length=30,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
                'placeholder': 'Subject'
            }
        ),
        validators=[
            validators.RegexValidator(
                regex='^[A-Za-z]{3,30}$', message="Must be valid...")
        ]
    )
    message = forms.CharField(
        label='Message',
        max_length=500,
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'placeholder': 'Message',
                'cols': '30',
                'rows': '7',
            }
        )
    )

    class Meta:
        model = Contact
        fields = [
            'name',
            'email',
            'subject',
            'message'
        ]

greenGrocery/contact/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import ContactForm

# Create your views here.


@login_required
def contact_page(request):
    contact_form = ContactForm()
    if request.method == 'POST':
        contact_form = ContactForm(request.POST)
        if contact_form.is_valid():
            contact_form.save()
            messages.success(
                request, 'Thank you for contacting us. We will reach out to you soon.')
    return render(request, 'contact.html', {
        'contact_form': contact_form,
    })

greenGrocery/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}

<div class="hero-wrap hero-bread" style="background-image: url('{% static 'images/market-4.jpg' %}');">
  <div class="container">
    <div class="row no-gutters slider-text align-items-center justify-content-center">
      <div class="col-md-9 ftco-animate text-center">
        <p class="breadcrumbs">
          <span class="mr-2"><a href="index.html">Home</a></span>
          <span>About us</span>
        </p>
        <h1 class="mb-0 bread">About us</h1>
      </div>
    </div>
  </div>
</div>

<section class="ftco-section about-section ftco-no-pb ftco-no-pt">
  <div class="container py-4">
    <div class="row">
      <div class="col-md-7 container text-center p-5 ftco-animate styled-border">
        <h1 class="mb-3">
          Introducing
          <a href="{% url 'index' %}" class="text-primary translate-up d-inline-block">GetReads.com
          </a>
        </h1>
        <p class="lead">
          We deliver all types of New and Old
          <strong class="text-danger">Books and Novels</strong> at your
          doorstep with
          <strong class="text-danger">lowest price</strong> possible and retain
          <strong class="text-danger">100% of quality</strong> products.
        </p>

        <h1 class="mt-5 mb-3">
          Large range of
          <span class="text-primary translate-up d-inline-block">Authentic</span>
          and
          <span class="text-primary translate-up d-inline-block">Latest</span>
          Books
        </h1>
        <p class="lead">
          We provide best range of
          <strong class="text-danger">Authentic and Latest</strong>
          Books from best Authors, directly imported 
          delivered to your doorstep. All our products are
          <strong class="text-danger">Original</strong> and
          <strong class="text-danger">Handpicked</strong> for you to
          maintain premium quality.
        </p>
      </div>
    </div>
  </div>
</section>
{% endblock %}

greenGrocery/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <title>GetReads - Your Online Book Shop</title>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-162407521-1"></script>
  <script src="{% static 'js/gtag.js' %}"></script>
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans:300,400,400i|Nunito:300,300i" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap"
    rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet" />
  <link rel="stylesheet" href="{% static 'css/open-iconic-bootstrap.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/animate.css' %}" />

  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}" />
  <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}" />

  <link rel="stylesheet" href="{% static 'css/aos.css' %}" />

  <link rel="stylesheet" href="{% static 'css/ionicons.min.css' %}" />

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}" />
  <link rel="stylesheet" href="{% static 'css/jquery.timepicker.css' %}" />

  <link rel="stylesheet" href="{% static 'css/flaticon.css' %}" />
  <link rel="stylesheet" href="{% static  'css/icomoon.css' %}" />

  <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" href="{% static 'css/stripe.css' %}" />
  <script src="https://js.stripe.com/v3/"></script>
</head>

<body class="goto-here">
  <div class="py-1 bg-primary d-none d-lg-block">
    <div class="container">
      <div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
        <div class="col-lg-12 d-block">
          <div class="row d-flex">
            <div class="col-md pr-4 d-flex topper align-items-center">
              <div class="icon mr-2 d-flex justify-content-center align-items-center">
                <span class="icon-phone2"></span>
              </div>
              <span class="text">+91 960 9609 123</span>
            </div>
            <div class="col-md pr-4 d-flex topper align-items-center">
              <div class="icon mr-2 d-flex justify-content-center align-items-center">
                <span class="icon-paper-plane"></span>
              </div>
              <span class="text">mail@GetReads.com</span>
            </div>
            <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
              <span class="text">1 day delivery guranteed</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
      <a class="navbar-brand" href="{% url 'index' %}">GetReads</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
        aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span> Menu
      </button>

      <div class="collapse navbar-collapse" id="ftco-nav">
        <ul class="navbar-nav ml-auto">
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown04" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">Books</a>
            <div class="dropdown-menu" aria-labelledby="dropdown04">
              <a class="dropdown-item" href="{% url 'products:products' %}">Genre</a>
              <!-- <a class="dropdown-item" href="wishlist.html">Wishlist</a> -->
              <!-- <a class="dropdown-item" href="product-single.html"
                  >Single Product</a
                > -->
              
            </div>
          </li>
          <li class="nav-item {% if btn == 'about' %} active {% endif %}">
            <a href="{% url "about" %}" class="nav-link">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'contact:contact' %}" class="nav-link">Contact</a>
          </li>
          <li class="nav-item cta cta-colored">
            <a href="{% url 'carts:cart' %}" class="nav-link d-inline-block px-2"><span
                class="icon-shopping_cart"></span>[<span
                class="navbar-cart-count">{{ request.session.cart_items_total }}</span>]</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="" id="dropdown05" data-toggle="dropdown" aria-haspopup="true"
              aria-expanded="false">
              {% if user.first_name %}
              {{ user.first_name }}
              {% else %}
              {{ user.username }}
              {% endif %}
            </a>
            <div class="dropdown-menu" aria-labelledby="dropdown05">
              <a class="dropdown-item" href="{% url 'index' %}">Profile</a>
              <a class="dropdown-item" href="{% url 'user:logout' %}">Logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item {% if btn == 'login' %} active {% endif %}">
            <a href="{% url 'user:login' %}" class="nav-link">
              Login
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'contact:contact' %}" class="nav-link">Contact</a>
          </li>
          <li class="nav-item cta cta-colored">
            <a href="{% url 'carts:cart' %}" class="nav-link d-inline-block px-2"><span
                class="icon-shopping_cart"></span>[<span
                class="navbar-cart-count">{{ request.session.cart_items_total }}</span>]</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- END nav -->

  {% block body_block %}

  {% endblock %}

  <!-- <hr /> -->

  <section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
    <div class="container py-4">
      <div class="row d-flex justify-content-around py-5">
        <!-- <div class="col-md-6">
          <h2 style="font-size: 22px;" class="mb-0">
            Subcribe to our Newsletter
          </h2>
          <span>Get e-mail updates about our latest products and special
            offers</span>
        </div>
        <div class="col-md-6 d-flex align-items-end">
          <form action="#" class="subscribe-form">
            <div class="form-group d-flex">
              <input type="text" class="form-control" placeholder="Enter email address" />
              <input type="submit" value="Click here to Subscribe!" class="submit px-3" />
            </div>
          </form>
        </div> -->
        <div class="text-center col-8">
          <h2 style="font-size: 22px;" class="mb-0">
            Subcribe to our Newsletter
          </h2>
          <span>Get e-mail updates about our latest products and special
            offers</span>
        </div>
        <div class="col-4">
          <a href="https://mailchi.mp/00ab2e910e09/greengrocery">
            <button class="btn btn-primary styled-border p-3">Click here to Subscribe!</button>
          </a>
        </div>
      </div>
    </div>
  </section>

  <footer class="ftco-footer ftco-section">
    <div class="container">
      <div class="row">
        <div class="mouse">
          <a href="#" class="mouse-icon">
            <div class="mouse-wheel">
              <span class="ion-ios-arrow-up"></span>
            </div>
          </a>
        </div>
      </div>
      <div class="row mb-5">
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">GetReads</h2>
            <p>
              We provide Best Books 
              <strong class="text-primary">in all Categories</strong>
              from all the best Authors, directly imported and safely
              delivered to your doorstep.
            </p>
            <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
              <li class="ftco-animate">
                <a href="#"><span class="icon-twitter"></span></a>
              </li>
              <li class="ftco-animate">
                <a href="#"><span class="icon-facebook"></span></a>
              </li>
              <li class="ftco-animate">
                <a href="#"><span class="icon-instagram"></span></a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4 ml-md-5">
            <h2 class="ftco-heading-2">Menu</h2>
            <ul class="list-unstyled">
              <li><a href="{% url 'products:products' %}" class="py-2 d-block">Books</a></li>
              <li><a href="{% url 'about' %}" class="py-2 d-block">About</a></li>
              <li><a href="#" class="py-2 d-block">Support</a></li>
              <li><a href="#" class="py-2 d-block">Contact Us</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Help</h2>
            <div class="d-flex">
              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
                <li>
                  <a href="#" class="py-2 d-block">Delivery Information</a>
                </li>
                <li>
                  <a href="#" class="py-2 d-block">FAQs</a>
                </li>
                <li>
                  <a href="#" class="py-2 d-block">Terms &amp; Conditions</a>
                </li>
                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="col-md">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Have a Question?</h2>
            <div class="block-23 mb-3">
              <ul>
                <li>
                  <span class="icon icon-map-marker"></span><span class="text">203 Shilp Aaron, Ahmedabad, Gujarat,
                    India</span>
                </li>
                <li>
                  <a href="#"><span class="icon icon-phone"></span><span class="text">+91 960 9609 123</span></a>
                </li>
                <li>
                  <a href="#"><span class="icon icon-envelope"></span><span
                      class="text">mail@GetReads.com</span></a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12 text-center">
          <p>
            Copyright &copy;
            <script>
              document.write(new Date().getFullYear());
            </script>
            All rights reserved | This website is made with
             <i class="icon-heart color-danger" aria-hidden="true"></i> by Team of
            <a href="#" target="_blank">GetReads</a> in Gujarat, India.
          </p>
        </div>
      </div>
    </div>
  </footer>

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
      <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
      <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
        stroke="#F96D00" />
    </svg>
  </div>

  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
  <script src="{% static 'js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
  <script src="{% static 'js/aos.js' %}"></script>
  <script src="{% static 'js/jquery.animateNumber.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datepicker.js' %}"></script>
  <script src="{% static 'js/scrollax.min.js' %}"></script>
  <script src="{% static 'js/stripe-form.js' %}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false">
  </script>
  <script src="{% static 'js/google-map.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

greenGrocery/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block body_block %}
{% comment %} {% load extras %} {% endcomment %}
<section id="home-section" class="hero">
  <div class="home-slider owl-carousel">
    <div class="slider-item" style="background-image: url('{% static 'images/bg_1.jpg' %}');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">
          <div class="col-md-12 ftco-animate text-center">
            <h1 class="mb-2">We sell Best Books &amp; Novels</h1>
            <h2 class="subheading mb-4">
              We deliver original Books &amp; Novels
            </h2>
            <p>
              <a href="{% url 'about' %}" class="btn btn-primary styled-border">View Details</a>
            </p>
          </div>
        </div>
      </div>
    </div>

    <div class="slider-item" style="background-image: url('{% static 'images/5-edited.jpg' %}');">
      <div class="overlay"></div>
      <div class="container">
        <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">
          <div class="col-sm-12 ftco-animate text-center">
            <h1 class="mb-2">100% Original &amp; boxed Books</h1>
            <h2 class="subheading mb-4">
              We deliver original Books &amp; Novels
            </h2>
            <p>
              <a href="{% url 'about' %}" class="btn btn-primary styled-border">View Details</a>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section">
  <div class="container">
    <div class="row no-gutters ftco-services">
      <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
        <div class="media block-6 services mb-md-0 mb-4">
          <div class="icon bg-color-1 active d-flex justify-content-center align-items-center mb-2">
            <span class="flaticon-shipped"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Free Shipping</h3>
            <span>On order over ₹1000</span>
          </div>
        </div>
      </div>
      <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
        <div class="media block-6 services mb-md-0 mb-4">
          <div class="icon bg-color-2 d-flex justify-content-center align-items-center mb-2">
            <span class="flaticon-diet"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">100% Original</h3>
            <span>Product well packaged</span>
          </div>
        </div>
      </div>
      <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
        <div class="media block-6 services mb-md-0 mb-4">
          <div class="icon bg-color-3 d-flex justify-content-center align-items-center mb-2">
            <span class="flaticon-award"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Superior Quality</h3>
            <span>Quality Products</span>
          </div>
        </div>
      </div>
      <div class="col-md-3 text-center d-flex align-self-stretch ftco-animate">
        <div class="media block-6 services mb-md-0 mb-4">
          <div class="icon bg-color-4 d-flex justify-content-center align-items-center mb-2">
            <span class="flaticon-customer-service"></span>
          </div>
          <div class="media-body">
            <h3 class="heading">Support</h3>
            <span>24/7 Support</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section ftco-category ftco-no-pt">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row">
          <div class="col-md-6 order-md-last align-items-stretch d-flex">
            <div class="category-wrap-2 ftco-animate img align-self-stretch d-flex"
              style="background-image: url('{% static 'images/books1.jpg' %}');">
              <div class="text text-center">
                <h2>Books</h2>
                <p>"A Room without Books is like a Body without Soul" - Cicero</p>
                <p>
                  <a href="{% url 'products:products' %}" class="btn btn-primary styled-border">Buy now</a>
                </p>
              </div>
            </div>
          </div>
          <div class="col-md-6">
            <div class="category-wrap ftco-animate img mb-4 d-flex align-items-end"
              style="background-image: url('{% static 'images/books.jpg' %}');">
              <div class="text px-3 py-1">
                <h2 class="mb-0"><a href="{% url 'products:vegetables' %}">Books</a></h2>
              </div>
            </div>
            <div class="category-wrap ftco-animate img d-flex align-items-end"
              style="background-image: url('{% static 'images/novels.jpg' %}');">
              <div class="text px-3 py-1">
                <h2 class="mb-0"><a href="{% url 'products:fruits' %}">Novels</a></h2>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="ftco-section">
  <div class="container">
    <div class="row justify-content-center mb-3 pb-3">
      <div class="col-md-12 heading-section text-center ftco-animate">
        <span class="subheading">Products</span>
        <h2 class="mb-4">Our Featured Products</h2>
        <p class="lead">
         Best Books and Novels now made easily
          available at your doorstep.
        </p>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      {% for item in qs %}
      <div class="col-md-6 col-lg-3 ftco-animate">
        <div class="product">
          <a href="{% url 'products:featured' item.slug %}"
            class="add-to-cart d-flex justify-content-center align-items-center text-center">
            <span class="img-prod"><img class="img-fluid" src="{{ item.image.url }}" alt="" />
              {% if item.on_sale %}
              <span class="status">{{ item.discount }}%</span>
              {% endif %}
              <div class="overlay"></div>
            </span>
          </a>
          <div class="text py-3 pb-4 px-3 text-center">
            <h3>{{ item.title }}</h3>
            <div class="d-flex">
              <div class="pricing">
                <p class="price">
                  {% if item.on_sale %}
                  <span class="mr-2 price-dc">₹{{ item.price }}</span><span
                    class="price-sale">₹{{ item.discounted_price }}</span>
                  {% else %}
                  <span>₹{{item.price}}</span>
                  {% endif %}
                </p>
              </div>
            </div>
            <div class="bottom-area d-flex px-3">
              <div class="m-auto d-flex">
                <a href="{% url 'products:featured' item.slug %}"
                  class="add-to-cart d-flex justify-content-center align-items-center text-center">
                  <span><i class="ion-ios-menu"></i></span>
                </a>
                <!-- <a href="#" class="buy-now d-flex justify-content-center align-items-center mx-1">
                  <span><i class="ion-ios-cart"></i></span>
                </a> -->
              </div>
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>


<section class="ftco-section subscription-section">
  <div class="container">
    <div class="row justify-content-center mb-5">
      <div class="col-md-7 heading-section ftco-animate text-center">
        <span class="subheading">Subscriptions</span>
        <h2 class="mb-4">
          Want hassle free Books and Novels at your home?
        </h2>
        <p class="">
          Just select one of our packages and relax back at home without
          being concerned about the prices.
        </p>
      </div>
    </div>
    <div class="row ftco-animate">
      <div class="col-md-12">
        <div class="carousel-subscription owl-carousel">
          <div class="item">
            <div class="card px-3 pt-3 text-center styled-border styled-border--lined__thin">
              <h1 class="border-bottom p-3 text-primary">Standard</h1>
              <p class="lead p-3 text-info border-bottom">
                ₹1550/Month
              </p>
              <ul class="list-unstyled p-3 text-primary">
                <li class="pb-2">Upto 4 Books</li>
                
                <li class="p-2">Any books under ₹500 </li>
                <li class="p-2">Free Home Delivery</li>
              </ul>
            </div>
          </div>
          <div class="item">
            <div class="card px-3 pt-3 text-center styled-border styled-border--lined__thin">
              <h1 class="border-bottom p-3 text-primary">
               Premium
              </h1>
              <p class="lead p-3 text-info border-bottom">
                ₹2850/Month
              </p>
              <ul class="list-unstyled p-3 text-primary">
                <li class="pb-2">Upto 6 Books</li>
                <li class="p-2">Any Books under ₹600</li>
                <li class="p-2">Free Home Delivery</li>
              </ul>
            </div>
          </div>
          <div class="item">
            <div class="card px-3 pt-3 text-center styled-border styled-border--lined__thin">
              <h1 class="border-bottom p-3 text-primary">
               Premium (Yearly)
              </h1>
              <p class="lead p-3 text-info border-bottom">
                ₹30000/Year
              </p>
              <ul class="list-unstyled p-3 text-primary">
                <li class="pb-2">Unlimited Books*(6 per Month)</li>
                <li class="p-2">No Price limits</li>
                <li class="p-2">Free Home Delivery</li>
            
              </ul>
            </div>
          </div>
          <div class="item">
            <div class="card px-3 pt-3 text-center styled-border styled-border--lined__thin">
              <h1 class="border-bottom p-3 text-primary">Regular</h1>
              <p class="lead p-3 text-info border-bottom">
                ₹750/Month
              </p>
              <ul class="list-unstyled p-3 text-primary">
                <li class="pb-2">Upto 2 Books</li>

                <li class="p-2">Any Books under ₹400 </li>
                <li class="p-2">50% Discount on Home Delivery</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center mt-5 my-3 ftco-animate">
    <h5>
      <a class="btn btn-primary styled-border translate-up d-inline-block" href="subscription.html" role="button">Know
        More</a>
    </h5>
  </div>
</section>
{% endblock %}